package tellets
import "time"

type Meta struct {
	// Required
	Title       string  `json:"title,omitempty"`
	Categories  []string`json:"categories,omitempty"`
	Tags        []string`json:"tags,omitempty"`
	Date        *time.Time`json:"date,omitempty"`
	LastModifiedDate *time.Time`json:"lastModifiedDate,omitempty"`
	State       string  `json:"state,omitempty"`
	// Generated by title
	Link        string  `json:"link,omitempty"`
	PermLink    string  `json:"permLink,omitempty"`
	Features    []string
	Format      string  `json:"format,omitempty"`
	// Key to find an article
	Hash        string  `json:"hash,omitempty"`
	// wener<wener@wener.me>(http://hi.wener.me)
	Author      []string`json:"author,omitempty"`
	// Optional option
	Option      map[string]string`json:"option,omitempty"`
	Summary     string  `json:"summary,omitempty"`
}
type ArticleState string
type ContentFormat string
type Feature string

const (
	PUBLISHED   ArticleState = "PUBLISHED"
	DRAFT       ArticleState = "DRAFT"
)

