package tellets
import "time"

type (
MetaParser interface {
	Parse(string) (Meta, error)
	CanParse(filename string) bool
	Name() string
}
MetaParserManager interface {

}
)

type Meta struct {
	// Required
	Title string
	Categories []string
	Tags []string
	Date *time.Time
	LastModifiedDate *time.Time
	State string
	// Generated by title
	Link string
	PermLink string
	Features []string
	Format string
	// Key to find an article
	Sha1 string
	// wener<wener@wener.me>(http://hi.wener.me)
	Author []string
	// Optional option
	Option map[string]string
	Summary string
}
type ArticleState string
type ContentFormat string
type Feature string

const (
	PUBLISHED   ArticleState = "PUBLISHED"
	DRAFT       ArticleState = "DRAFT"
)

type MetaStorage interface {
	FindBySha(string) Meta
	FindByLink(string) Meta
	FindByTags([]string) []Meta
	FindByCategories([]string) []Meta
}

